[#184281154] Fix rebuilds can cause state corruption
alphagov/paas-bootstrap pull request #574
Opened 2023-03-14 17:40 UTC by malcgds

What
----

The [pivotal storey](https://www.pivotaltracker.com/n/projects/1275640/stories/184281154) provides the detail.

The create-bosh-concourse pipeline has been changed such that Terraform is now configured with its own backend and is no longer reliant on the pipeline providing and saving its state via resources.

I have also used the aws cli to pull down a file from an s3 bucket to obtain the current bosh manifest state.

How to review
-------------

1 - Review the code.
2 - Run the branch through a dev env (I've tested this branch on 1).
3 - After the run, check the size of the files (bosh.tfstate, bosh-manifest-state-(region).json, concourse.tfstate, bootstrap-cyber.tfstate, vpc.tfstate) in the appropriate bucket for the env e.g. for dev01 the bucket would be gds-paas-dev01-state

Who can review
--------------

Not me.

---

🚨⚠️ Please do not merge this pull request via the GitHub UI ⚠️🚨

2023-03-17 12:03 UTC, cadmiumcat commented
This PR has the changes from https://github.com/alphagov/paas-bootstrap/pull/568. If that's needed here, it'd be helpful to have them at least as a different commit so that it's easier to review the changes for _this_ PR

2023-03-17 12:07 UTC, cadmiumcat requested changes
See my first comment

2023-03-17 12:58 UTC, malcgds commented
Ooh yes, I hadn't thought of the impact on the reviewer.

2023-03-20 08:18 UTC, closed without merging

2023-03-20 08:18 UTC, malcgds commented
Need to provide separate commits